
import java.awt.Color;
//import static javafx.scene.paint.Color.color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KKKK
 */
public class HomePg extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public HomePg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel25 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        HeadP = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        HomePg = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Borrow1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        SearchTf = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        UploadPg = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        GenreTF = new javax.swing.JTextField();
        AuthTF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ta1 = new javax.swing.JTextArea();
        TypeCmb = new javax.swing.JComboBox<>();
        TimeCmb = new javax.swing.JComboBox<>();
        uploadBtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        BorrowhPg = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        HisTb = new javax.swing.JTable();
        jLabel52 = new javax.swing.JLabel();
        UploadhPg = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UploadHisT = new javax.swing.JTable();
        jLabel53 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        UserLbl = new javax.swing.JLabel();
        eLbl = new javax.swing.JLabel();
        genLbl = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        HistoryBtn = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        UploadBtn = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        LendHistoryBtn = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setLocation(new java.awt.Point(300, 25));
        jDialog1.setUndecorated(true);
        jDialog1.setSize(new java.awt.Dimension(900, 700));
        jDialog1.setType(java.awt.Window.Type.POPUP);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialog1WindowActivated(evt);
            }
        });
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(102, 102, 102));
        jPanel25.setOpaque(false);
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Name of book");
        jPanel25.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 96, -1, -1));

        jLabel55.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Author");
        jPanel25.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 172, -1, -1));

        jLabel56.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Time Period");
        jPanel25.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, -1, -1));

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Name of lender");
        jPanel25.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, -1, -1));

        jLabel58.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Phone Number");
        jPanel25.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 454, -1, -1));

        jLabel59.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Genre");
        jPanel25.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel60.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Type");
        jPanel25.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel61.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("E-mail");
        jPanel25.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        lbl1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("jLabel62");
        jPanel25.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 96, 242, 49));

        lbl3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("jLabel63");
        jPanel25.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 172, 242, -1));

        lbl2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("jLabel64");
        jPanel25.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 185, -1));

        lbl4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("jLabel65");
        jPanel25.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 252, 42));

        lbl5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("jLabel66");
        jPanel25.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 268, 242, -1));

        lbl6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("jLabel67");
        jPanel25.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 367, 443, -1));

        lbl7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 255, 255));
        lbl7.setText("jLabel68");
        jPanel25.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 454, 223, -1));

        lbl8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("jLabel69");
        jPanel25.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 272, -1));

        jLabel70.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Description");
        jPanel25.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 726, 67));

        jLabel64.setFont(new java.awt.Font("Trebuchet MS", 0, 100)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("X");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel25.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 90, 110));

        jDialog1.getContentPane().add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        ConfirmBtn.setBackground(new java.awt.Color(204, 204, 204));
        ConfirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmBtnMouseClicked(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Confirm");

        javax.swing.GroupLayout ConfirmBtnLayout = new javax.swing.GroupLayout(ConfirmBtn);
        ConfirmBtn.setLayout(ConfirmBtnLayout);
        ConfirmBtnLayout.setHorizontalGroup(
            ConfirmBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        ConfirmBtnLayout.setVerticalGroup(
            ConfirmBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmBtnLayout.createSequentialGroup()
                .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog1.getContentPane().add(ConfirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 360, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Calm Darya.jpg"))); // NOI18N
        jDialog1.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbl9.setForeground(new java.awt.Color(153, 0, 255));
        jDialog1.getContentPane().add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        lbl10.setForeground(new java.awt.Color(102, 153, 255));
        lbl10.setText("jLabel64");
        jDialog1.getContentPane().add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 30, 0, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeadP.setBackground(new java.awt.Color(255, 255, 255));
        HeadP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        HeadP.setFocusable(false);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/topbg1.jpg"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Prac.JPG"))); // NOI18N

        javax.swing.GroupLayout HeadPLayout = new javax.swing.GroupLayout(HeadP);
        HeadP.setLayout(HeadPLayout);
        HeadPLayout.setHorizontalGroup(
            HeadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
        );
        HeadPLayout.setVerticalGroup(
            HeadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, Short.MAX_VALUE)
        );

        getContentPane().add(HeadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1120, 140));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        HomePg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Borrow1.setBackground(new java.awt.Color(0, 153, 255));
        Borrow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Borrow1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Borrow");

        javax.swing.GroupLayout Borrow1Layout = new javax.swing.GroupLayout(Borrow1);
        Borrow1.setLayout(Borrow1Layout);
        Borrow1Layout.setHorizontalGroup(
            Borrow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Borrow1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Borrow1Layout.setVerticalGroup(
            Borrow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(Borrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/the girl.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 270));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 380));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.jpg"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, -1));

        jPanel11.setBackground(new java.awt.Color(0, 153, 255));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Borrow");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 240, 380));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anonymous.jpg"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, -1));
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 190, -1));

        jPanel16.setBackground(new java.awt.Color(0, 153, 255));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Borrow");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 260, 380));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/the water.jpg"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jPanel17.setBackground(new java.awt.Color(0, 153, 255));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Borrow");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 260, 380));

        jPanel13.setOpaque(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lost girls.jpg"))); // NOI18N

        jPanel18.setBackground(new java.awt.Color(0, 153, 255));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Borrow");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 250, 370));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/becoming.jpg"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 270));

        jLabel10.setText("Borrow");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 375, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 153, 255));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Borrow");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 270, 370));

        jPanel14.setOpaque(false);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/night tiger.jpg"))); // NOI18N

        jPanel19.setBackground(new java.awt.Color(0, 153, 255));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Borrow");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(72, 72, 72))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 0, 230, 350));

        jPanel6.setOpaque(false);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/suspect.jpg"))); // NOI18N

        jPanel20.setBackground(new java.awt.Color(0, 153, 255));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Borrow");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1900, 0, 280, 370));

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 402));

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        SearchTf.setForeground(new java.awt.Color(102, 102, 102));
        SearchTf.setText("Search names of books or author");
        SearchTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTfMouseClicked(evt);
            }
        });
        SearchTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTfActionPerformed(evt);
            }
        });

        SearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loupe.png"))); // NOI18N

        javax.swing.GroupLayout SearchBtnLayout = new javax.swing.GroupLayout(SearchBtn);
        SearchBtn.setLayout(SearchBtnLayout);
        SearchBtnLayout.setHorizontalGroup(
            SearchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchBtnLayout.setVerticalGroup(
            SearchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchTf, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "Name", "Type", "Author", "Genre", "Time Period", "Name of lender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.setRowHeight(30);
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tb1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 960, 720));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Influenza.jpg"))); // NOI18N
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1100, 780));

        jScrollPane2.setViewportView(jPanel2);

        HomePg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 610));

        jLayeredPane1.add(HomePg, "card2");

        UploadPg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Name of book");
        jPanel33.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel47.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Type of book");
        jPanel33.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel48.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Genre");
        jPanel33.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel49.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setText("Author");
        jPanel33.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel50.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("<html>\nTime for which you want to lend the book\n</html>");
        jPanel33.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 283, 86));

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("Comments");
        jPanel33.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 352, -1, 30));

        NameTF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel33.add(NameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 508, 56));

        GenreTF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel33.add(GenreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 508, 57));

        AuthTF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel33.add(AuthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 349, 51));

        Ta1.setColumns(20);
        Ta1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Ta1.setRows(5);
        jScrollPane3.setViewportView(Ta1);

        jPanel33.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 428, -1));

        TypeCmb.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School books(NCERT, Guides, Refreshers)", "Other Books(Novels,Guides,Cooking,Motivational,Biographies)" }));
        jPanel33.add(TypeCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 40));

        TimeCmb.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TimeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 ", "5 ", "7", "10 ", "14", "21", "30", "42", "60", "90", " " }));
        TimeCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeCmbActionPerformed(evt);
            }
        });
        jPanel33.add(TimeCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 142, 30));

        uploadBtn.setBackground(new java.awt.Color(204, 255, 255));
        uploadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadBtnMouseClicked(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload (1).png"))); // NOI18N
        jLabel22.setText("Upload");

        javax.swing.GroupLayout uploadBtnLayout = new javax.swing.GroupLayout(uploadBtn);
        uploadBtn.setLayout(uploadBtnLayout);
        uploadBtnLayout.setHorizontalGroup(
            uploadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uploadBtnLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        uploadBtnLayout.setVerticalGroup(
            uploadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel33.add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 260, 50));

        jLabel63.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel63.setText("Days");
        jPanel33.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 70, 30));

        UploadPg.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 930, 520));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Electric Violet.jpg"))); // NOI18N
        UploadPg.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 770));

        jLayeredPane1.add(UploadPg, "card4");

        BorrowhPg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HisTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order no.", "Name of book", "Author", "Type", "Time Period", "Time left"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HisTb.setRowHeight(40);
        HisTb.setShowHorizontalLines(false);
        HisTb.setShowVerticalLines(false);
        jScrollPane5.setViewportView(HisTb);

        BorrowhPg.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 960, 495));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Opa.jpg"))); // NOI18N
        BorrowhPg.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 650));

        jLayeredPane1.add(BorrowhPg, "card7");

        UploadhPg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UploadHisT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of book", "Type", "Author", "Genre", "Time Preiod", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UploadHisT.setRowHeight(40);
        UploadHisT.setRowMargin(3);
        UploadHisT.setShowHorizontalLines(false);
        UploadHisT.setShowVerticalLines(false);
        jScrollPane4.setViewportView(UploadHisT);

        UploadhPg.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 866, 471));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shroom Haze.jpg"))); // NOI18N
        UploadhPg.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        jLayeredPane1.add(UploadhPg, "card6");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 1120, 650));

        jPanel24.setBackground(new java.awt.Color(208, 36, 101));

        UserLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/man.png"))); // NOI18N

        eLbl.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        eLbl.setForeground(new java.awt.Color(255, 255, 255));
        eLbl.setText("Basulipratyus@gmail.com");

        genLbl.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        genLbl.setForeground(new java.awt.Color(255, 255, 255));
        genLbl.setText("Male");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Free user");

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/system-update.png"))); // NOI18N
        jLabel26.setText("Upgrade to prebooq pro");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genLbl))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(eLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(87, 87, 87))))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(genLbl))
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 130));

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutBtn.setBackground(new java.awt.Color(153, 153, 255));
        LogoutBtn.setOpaque(false);
        LogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseClicked(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Sign out");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N

        javax.swing.GroupLayout LogoutBtnLayout = new javax.swing.GroupLayout(LogoutBtn);
        LogoutBtn.setLayout(LogoutBtnLayout);
        LogoutBtnLayout.setHorizontalGroup(
            LogoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        LogoutBtnLayout.setVerticalGroup(
            LogoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoutBtnLayout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(LogoutBtnLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))))
        );

        jPanel30.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        HistoryBtn.setBackground(new java.awt.Color(153, 153, 255));
        HistoryBtn.setOpaque(false);
        HistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryBtnMouseClicked(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Your History");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/history.png"))); // NOI18N

        javax.swing.GroupLayout HistoryBtnLayout = new javax.swing.GroupLayout(HistoryBtn);
        HistoryBtn.setLayout(HistoryBtnLayout);
        HistoryBtnLayout.setHorizontalGroup(
            HistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel29)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        HistoryBtnLayout.setVerticalGroup(
            HistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel30.add(HistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 60));

        UploadBtn.setBackground(new java.awt.Color(153, 153, 255));
        UploadBtn.setOpaque(false);
        UploadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UploadBtnMouseClicked(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Upload");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload.png"))); // NOI18N

        javax.swing.GroupLayout UploadBtnLayout = new javax.swing.GroupLayout(UploadBtn);
        UploadBtn.setLayout(UploadBtnLayout);
        UploadBtnLayout.setHorizontalGroup(
            UploadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        UploadBtnLayout.setVerticalGroup(
            UploadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UploadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel30.add(UploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 50));

        LendHistoryBtn.setBackground(new java.awt.Color(153, 153, 255));
        LendHistoryBtn.setOpaque(false);
        LendHistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LendHistoryBtnMouseClicked(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("History of lending");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/service.png"))); // NOI18N

        javax.swing.GroupLayout LendHistoryBtnLayout = new javax.swing.GroupLayout(LendHistoryBtn);
        LendHistoryBtn.setLayout(LendHistoryBtnLayout);
        LendHistoryBtnLayout.setHorizontalGroup(
            LendHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LendHistoryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(19, 19, 19))
        );
        LendHistoryBtnLayout.setVerticalGroup(
            LendHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LendHistoryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel30.add(LendHistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 50));

        HomeBtn.setBackground(new java.awt.Color(153, 153, 255));
        HomeBtn.setOpaque(false);
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Home");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hme.png"))); // NOI18N

        javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
        HomeBtn.setLayout(HomeBtnLayout);
        HomeBtnLayout.setHorizontalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        HomeBtnLayout.setVerticalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(HomeBtnLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel27)))
                .addContainerGap())
        );

        jPanel30.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 60));

        jLabel33.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Need help?");
        jPanel30.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, 20));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 29)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("PreBooq");
        jPanel30.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 130, 40));

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Version 1.0");
        jPanel30.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 90, -1));

        jPanel32.setOpaque(false);

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Contact us");

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contact.png"))); // NOI18N

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(82, 82, 82))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addContainerGap())
            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel30.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 40));

        jPanel31.setOpaque(false);

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Help");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info.png"))); // NOI18N

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dance To Forget.jpg"))); // NOI18N
        jPanel30.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 620));

        getContentPane().add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    data d=new data();
    
    private void search(){
        DefaultTableModel mod = (DefaultTableModel) tb1.getModel();
        String search=SearchTf.getText();//gets data from search bar
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prebooq","root", "root");
            
            Statement st=con.createStatement();
            String sql="select*from books where name like'%"+search+"%' or author like'%"+search+"%' and status='A' ;";
            ResultSet rs=st.executeQuery(sql);//executes the code in mysql
            
            { int row=mod.getRowCount();
                if (row>0)
                {for(int i=0;i<row;i++)
                    mod.removeRow(0);}
            }//clears the table
            
            while(rs.next()){
                String s=rs.getString(1);
                String name=rs.getString(2);
                 String type=rs.getString(3);
                String author=rs.getString(4);
                String genre=rs.getString(5);
                String timeP=rs.getString(6);
                String seller=rs.getString(8);
               
                mod.addRow(new Object[]{s,name,type,author,genre,timeP,seller});
            //adds new row to the table
            }
            rs.close();
            st.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }
    
    private void special(String n,String sn){
          jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setOpacity(0.95f);//opens the confirm dialog box
        
         System.out.print("done");
     try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prebooq","root", "root");
            
            Statement st=con.createStatement();
            String sql="select*from books where name='"+n+"' or sno="+sn+";";
            ResultSet rs=st.executeQuery(sql);//retrieves the data of books
            
            while(rs.next()){
                String sno=rs.getString(1);
                String name=rs.getString(2);
                String type=rs.getString(3);
                String author=rs.getString(4);
                String genre=rs.getString(5);
                String timeP=rs.getString(6);
                String seller=rs.getString(8);
                String contact=rs.getString(9);
                String mail=rs.getString(10);
                String lenderno=rs.getString(11);
                //enters the data in the dialog window
                lbl1.setText(""+name);
                lbl2.setText(""+type);
                lbl3.setText(""+author);
                lbl4.setText(""+genre);
                lbl5.setText(""+timeP);   
                lbl6.setText(seller);
                lbl7.setText(""+contact);
                lbl8.setText(mail);
                lbl9.setText(lenderno);
                lbl10.setText(sno);
            }
            rs.close();
            st.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void LogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseClicked
        LoginP l=new LoginP();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
       HomePg.setVisible(true);//opens home tab
       UploadPg.setVisible(false);
       BorrowhPg.setVisible(false);
       UploadhPg.setVisible(false);
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void UploadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UploadBtnMouseClicked
        HomePg.setVisible(false);
       UploadPg.setVisible(true);//opens upload tab
       BorrowhPg.setVisible(false);
       UploadhPg.setVisible(false);
    }//GEN-LAST:event_UploadBtnMouseClicked

    private void HistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryBtnMouseClicked
         HomePg.setVisible(false);
       UploadPg.setVisible(false);
       BorrowhPg.setVisible(true);//opens history tab
       UploadhPg.setVisible(false);
       
        DefaultTableModel mod=(DefaultTableModel)HisTb.getModel();
        { int row=mod.getRowCount();
                if (row>0)
                {for(int i=0;i<row;i++)
                    mod.removeRow(0);
                }//clears the table in history tab 
          }
            //retrieves the users history(borrow)
        try{ Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prebooq","root", "root");
            Statement st=con.createStatement();
            String sql="select orderno,name,author,type,timep,date(sysdate())-time from trans where borrower like'%"+d.Sno+"%';";
            ResultSet rs=st.executeQuery(sql);

            while(rs.next()){
                String order=rs.getString(1);
                String name=rs.getString(2);
                String author=rs.getString(3);
                String type=rs.getString(4);
                Integer timep=rs.getInt(5);
                Integer time=rs.getInt(6);
                
                
                mod.addRow(new Object[]{order,name,author,type,timep,timep-time});
                //adds the new row
            }
            rs.close();
            st.close();
            con.close();         }
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_HistoryBtnMouseClicked

    private void LendHistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LendHistoryBtnMouseClicked
        HomePg.setVisible(false);
       UploadPg.setVisible(false);
       BorrowhPg.setVisible(false);
       UploadhPg.setVisible(true);//opens history(lending) tab
       
         DefaultTableModel mod=(DefaultTableModel)UploadHisT.getModel();
        { int row=mod.getRowCount();
                if (row>0)
                {for(int i=0;i<row;i++)
                    mod.removeRow(0);
                }//clears the table in history tab
          }
        //retrieves the users history(lend)
        try{ Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prebooq","root", "root");
            Statement st=con.createStatement();
            String sql="select name,type,author,genre,timep,status from books where name_lender like'%"+d.name+"%';";
            ResultSet rs=st.executeQuery(sql);

            while(rs.next()){
                String name=rs.getString(1);
                String type=rs.getString(2);
                String author=rs.getString(3);
                String genre=rs.getString(4);
                String timep=rs.getString(5);
                String status=rs.getString(6);

                mod.addRow(new Object[]{name,type,author,genre,timep,status});
            }//adds the new row

            rs.close();
            st.close();
            con.close();         }
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_LendHistoryBtnMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        eLbl.setText(data.mail);
       genLbl.setText(data.gender);
       
       ImageIcon I1=new ImageIcon(getClass().getResource("/Images/man.png"));
       ImageIcon I2=new ImageIcon(getClass().getResource("/Images/woman.png"));
       if(data.gender.equals("M"))
        UserLbl.setIcon(I1);
       else
        UserLbl.setIcon(I2);
    }//GEN-LAST:event_formWindowActivated

    private void uploadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadBtnMouseClicked
        String name=NameTF.getText();
        int Type=TypeCmb.getSelectedIndex();
        String genre =GenreTF.getText();
        String auth=AuthTF.getText();
        String time=(String)TimeCmb.getSelectedItem();
        String type;
        //retrieves the data
        if(Type==0)
            type="SB";
        else
            type="NSB";
            //sets type of book
        
         try{
                Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prebooq","root", "root");
                   Statement st=con.createStatement();
                   
                   String sql="insert into books(Name,type,author,genre,timeP,status,name_lender,contact,email,lenderno) values('"+name+"','"+type+"','"+auth+"','"+genre+"','"+time+"','A','"+d.name+"','"+d.mob_no+"','"+d.mail+"','"+d.Sno+"');" ;
                   st.executeUpdate(sql);//enters data of the book in the table
                   
                   JOptionPane.showMessageDialog(this, "Upload Successful");
                   
                   st.close();
                   con.close();
                   
                   //clears the textfields
                   NameTF.setText("");
                   TypeCmb.setSelectedIndex(-1);
                   GenreTF.setText("");
                   AuthTF.setText("");
                   TimeCmb.setSelectedIndex(-1);
                   Ta1.setText("");
        
         }
         catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
        
    }//GEN-LAST:event_uploadBtnMouseClicked

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        search();//calls yhe search method
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void jDialog1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowActivated
         DefaultTableModel dlm= (DefaultTableModel)tb1.getModel();
        
        String sn=(String)dlm.getValueAt(tb1.getSelectedRow(),0);
        special(null,sn);
        
    }//GEN-LAST:event_jDialog1WindowActivated

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setOpacity(0.95f);
    }//GEN-LAST:event_tb1MouseClicked

    private void ConfirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmBtnMouseClicked
      
                try{
                Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prebooq","root", "root");
                   Statement st=con.createStatement();
                   
                   String sql="insert into trans(name,author,type,timep,lender,borrower,time) values('"+lbl1.getText()+"','"+lbl3.getText()+"','"+lbl2.getText()+"','"+lbl5.getText()+"','"+lbl9.getText()+"','"+d.Sno+"',+sysdate());" ;
                   String sql1="update books set status='NA' where sno='"+lbl10.getText()+"' ;";
                   st.executeUpdate(sql);
                   st.executeUpdate(sql1);
                   
                   JOptionPane.showMessageDialog(this, "Upload Successful");
                   
                   st.close();
                   con.close();
                   
                   jDialog1.setVisible(false);
        
         }
         catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_ConfirmBtnMouseClicked

    private void SearchTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTfActionPerformed
        search();
    }//GEN-LAST:event_SearchTfActionPerformed

    private void SearchTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTfMouseClicked
       SearchTf.selectAll();
    }//GEN-LAST:event_SearchTfMouseClicked

    private void Borrow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow1MouseClicked
        special("The girl who knew too much",null);
    }//GEN-LAST:event_Borrow1MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        special("Something I never told you",null);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
       special("Becoming",null);
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        special("An Anyonymous Girl",null);
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        special("The water cure",null);
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        special("The lost girl of Paris",null);
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
       special("The night Tiger",null);
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
     special("The suspect",null);
    }//GEN-LAST:event_jPanel20MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jLabel64MouseClicked

    private void TimeCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
                            // Set System L&F
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthTF;
    private javax.swing.JPanel Borrow1;
    private javax.swing.JPanel BorrowhPg;
    private javax.swing.JPanel ConfirmBtn;
    private javax.swing.JTextField GenreTF;
    private javax.swing.JPanel HeadP;
    private javax.swing.JTable HisTb;
    private javax.swing.JPanel HistoryBtn;
    private javax.swing.JPanel HomeBtn;
    private javax.swing.JPanel HomePg;
    private javax.swing.JPanel LendHistoryBtn;
    private javax.swing.JPanel LogoutBtn;
    private javax.swing.JTextField NameTF;
    private javax.swing.JPanel SearchBtn;
    private javax.swing.JTextField SearchTf;
    private javax.swing.JTextArea Ta1;
    private javax.swing.JComboBox<String> TimeCmb;
    private javax.swing.JComboBox<String> TypeCmb;
    private javax.swing.JPanel UploadBtn;
    private javax.swing.JTable UploadHisT;
    private javax.swing.JPanel UploadPg;
    private javax.swing.JPanel UploadhPg;
    private javax.swing.JLabel UserLbl;
    private javax.swing.JLabel eLbl;
    private javax.swing.JLabel genLbl;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JTable tb1;
    private javax.swing.JPanel uploadBtn;
    // End of variables declaration//GEN-END:variables
}
